services:
  frontend:
    build:
      context: ./Application
    container_name: luxemart-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./Application:/app
      - /app/node_modules

  backend:
    build:
      context: ./server
    container_name: luxemart-backend
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: luxemart_user
      DB_PASSWORD: luxemart_password
      DB_NAME: luxemart_db
      DB_PORT: 5432
    volumes:
      - ./server:/app
      - /app/node_modules

  postgres:
    image: postgres:16
    container_name: luxemart-postgres
    environment:
      POSTGRES_USER: luxemart_user
      POSTGRES_PASSWORD: luxemart_password
      POSTGRES_DB: luxemart_db
    ports:
      - "5432:5432"
    volumes:
      - luxemart_postgres_data:/var/lib/postgresql/data
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: luxemart-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@luxemart.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  luxemart_postgres_data: