on:
  push:
    branches: [main]

  pull_request:

jobs:
  sast_scan:
    name: SAST - Semgrep
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: semgrep/semgrep-action@v1
        env:
          SEMGREP_FULL_SCAN: 1
        with:
          config: >
            p/security-audit
            p/owasp-top-ten
            p/secrets

  # sca_scan:
  #   name: SCA - Trivy
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Run Trivy
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         scan-type: fs
  #         scan-ref: .
  #         format: table
  #         severity: HIGH,CRITICAL
  #         exit-code: 1